packages:
  - 'adapters/*'
  - 'apps/*'
  - 'packages/*'
  - 'tools/packages/*'

supportedArchitectures:
  os:
    - win32
    - darwin
    - linux
  cpu:
    - x64
    - arm64
  libc:
    - glibc
    - musl

onlyBuiltDependencies:
  - '@cyclonedx/cdxgen-plugins-bin'
  - 'esbuild'
